// Generated by CoffeeScript 1.4.0
(function() {
  var Knout, root;

  Knout = (function() {

    function Knout(options) {
      this.options = options;
    }

    Knout.prototype.create_route = function() {};

    Knout.prototype.prepare_markers = function() {};

    return Knout;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Knout = Knout;

}).call(this);
