// Generated by CoffeeScript 1.4.0
(function() {
  var UI, root;

  UI = (function() {

    function UI(dugger) {
      this.dugger = dugger;
      this.bind_events();
      this.clean_form();
    }

    UI.prototype.bind_events = function() {
      var _this = this;
      $(".process-map-btn").click(function() {
        var url;
        if (_this.validate_map_source('#kml_url')) {
          url = $('#kml_url').val();
          url = 'https://maps.google.com/maps/ms?authuser=0&vps=2&ie=UTF8&msa=0&output=nl&msid=202130663253335322659.0004d8d93d20636c74095';
          _this.clean_form();
          return _this.dugger.load_map(url, function(data) {
            console.log(data);
            $('#loadMapModal').modal('hide');
            return _this.helper('Voila! Now you can start creating a route!');
          });
        }
      });
      $('#loadMapModal').on('hidden', function() {
        return _this.clean_modal();
      });
      return $('#loadMapModal').on('show', function() {
        return _this.clean_modal();
      });
    };

    UI.prototype.validate_map_source = function(dom) {
      return true;
      if ($(dom).val().length === 0) {
        $(dom).parent().addClass("error");
        return false;
      } else {
        $(dom).parent().removeClass("error");
        return true;
      }
    };

    UI.prototype.clean_modal = function() {
      $('#kml_url').parent().removeClass("error");
      return $('#kml_url').val('');
    };

    UI.prototype.clean_form = function() {
      this.clean_modal();
      return this.helper('Please load map to start creating routes!');
    };

    UI.prototype.helper = function(message) {
      if (!message) {
        return false;
      }
      return $('.sidebar-helper').html(message);
    };

    return UI;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.UI = UI;

}).call(this);
